### ISSUE TITLE
DB Structure Restoring

### ISSUE THREAD

**Issue by jeanlst** [mccarthysean/TimescaleDB-Backup-S3#3]
Hi,

I have a couple questions regarding the restore.. So does it only work for a newly created instance of postgre? That is the db that I'm trying to restore is empty (no tables, nothing)? Or can I do it on a live DB, that is it has the tables and data inside it and the restore would just drop everything and restore from the backup?

Second thing, I get these warnings on the daily backup. Is that normal?
```bash
2022/02/03 05:00:01 pg_dump: warning: there are circular foreign-key constraints on this table:
2022/02/03 05:00:01 pg_dump:   hypertable
2022/02/03 05:00:01 pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
2022/02/03 05:00:01 pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
2022/02/03 05:00:01 pg_dump: warning: there are circular foreign-key constraints on this table:
2022/02/03 05:00:01 pg_dump:   chunk
2022/02/03 05:00:01 pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
2022/02/03 05:00:01 pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
2022/02/03 05:00:01 pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
2022/02/03 05:00:01 DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
2022/02/03 05:00:01 HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
2022/02/03 05:00:01 pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
2022/02/03 05:00:01 DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
2022/02/03 05:00:01 HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
```

Finally, I might be wrong but I just tested a restore on a newly created postgre db and it restored all the data just fine and all. However, it did not restore any of the structure of my database. Tables constraints, indexes, triggers etc. Is there no way around this or did I restore it wrong?

**Comment by mccarthysean** [comment]
It's been a long time since I've looked at that, so maybe the following article will help.

Basically I just created a Docker container that allows a person to use ts-dump and ts-restore, so perhaps you would be better off asking the authors of those two programs?

https://mccarthysean.dev/upgrade-timescaledb-to-postgresql-13

Thanks,
Sean
________________________________
From: Jean Lucas ***@***.***>
Sent: Thursday, February 3, 2022 6:18:38 PM
To: mccarthysean/TimescaleDB-Backup-S3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mccarthysean/TimescaleDB-Backup-S3] DB Structure Restoring (Issue #3)


Hi,

I have a couple questions regarding the restore.. So does it only work for a newly created instance of postgre? That is the db that I'm trying to restore is empty (no tables, nothing)? Or can I do it on a live DB, that is it has the tables and data inside it and the restore would just drop everything and restore from the backup?

Second thing, I get these warnings on the daily backup. Is that normal?

2022/02/03 05:00:01 pg_dump: warning: there are circular foreign-key constraints on this table:
2022/02/03 05:00:01 pg_dump:   hypertable
2022/02/03 05:00:01 pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
2022/02/03 05:00:01 pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
2022/02/03 05:00:01 pg_dump: warning: there are circular foreign-key constraints on this table:
2022/02/03 05:00:01 pg_dump:   chunk
2022/02/03 05:00:01 pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
2022/02/03 05:00:01 pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
2022/02/03 05:00:01 pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
2022/02/03 05:00:01 DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
2022/02/03 05:00:01 HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
2022/02/03 05:00:01 pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
2022/02/03 05:00:01 DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
2022/02/03 05:00:01 HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.

Finally, I might be wrong but I just tested a restore on a newly created postgre db and it restored all the data just fine and all. However, it did not restore any of the structure of my database. Tables constraints, indexes, triggers etc. Is there no way around this or did I restore it wrong?

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmccarthysean%2FTimescaleDB-Backup-S3%2Fissues%2F3&data=04%7C01%7C%7Ca14702469e8546b4c4b308d9e77c4656%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637795343202621737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZTviko21UogX7rN1l20qLP9Nm%2FEPCUfqzcKQrfTIigM%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF37SZ55GDGG5PZ7ZS563QLUZMSO5ANCNFSM5NQPSHIA&data=04%7C01%7C%7Ca14702469e8546b4c4b308d9e77c4656%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637795343202621737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3Cv7H94opqn3JJR8aWyT9Vxh6xMCe9vzwm3hw5XjmvA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca14702469e8546b4c4b308d9e77c4656%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637795343202621737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Cl579%2BJOHCgW8KMGZoYMxCp%2Bu%2Fh%2FQ1tI0lO17QPAtJY%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca14702469e8546b4c4b308d9e77c4656%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637795343202621737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6z75Djjciw%2FIBDqd8%2FrLA8ob0sXBSgo1MmSZjeJXwUQ%3D&reserved=0>.

**Comment by jeanlst** [comment]
WIll do, thanks Sean. Quick question about your blog post. You mention `I didn’t want the database to be down for any length of time, so instead I backed up our existing database, then created a new PostgreSQL 13 database with a new Docker volume`, so this means that when you finished restoring to the new postgre db you just pointed your application to that new database? What did you do about the data that you received in your db between the point of your backup to the point were you restored it into a new instance?

**Comment by mccarthysean** [comment]
You can create a new backup at anytime, so if your database is currently working and you just want to move it or upgrade it, you wouldn't lose very much data. But this approach could potentially lose the most recent data after the backup was taken, yes

Thanks,
Sean
________________________________

**Comment by jeanlst** [comment]
Alright, thanks @mccarthysean
